### ISSUE TITLE
The plugin requires Auth token

### ISSUE THREAD

**Issue by T0nd0Tara** [Kurama622/profile.nvim#2]
I've tried to debug this plugin as I saw it didn't work on my machine.

and I noticed It requires the github authorization token to get the data through the graphql api.
I (and I believe many more) don't want to save locally tokens if we don't need to.
I think a better solution would be to get the contributions from `https://github.com/users/T0nd0Tara/contributions` url (that have all the necessary data).

And then parse it into the format the plugin need

**Comment by Kurama622** [comment]
I will consider your suggestion. Thank you.

**Comment by T0nd0Tara** [comment]
If you'd like I might be able to it myself in the near future. Using `sed`

**Comment by Kurama622** [comment]
Parsing contributions directly from https://github.com/users/T0nd0Tara/contributions may not be the best approach; using a third-party API might be better. Additionally, not using a token to fetch contributions could become a configurable option, with the default still relying on the token. The official API remains more reliable.

**Comment by T0nd0Tara** [comment]
I've found this third party API https://github.com/grubersjoe/github-contributions-api. That can provide contributions based on a range and in different formats.

If it's ok with you I'll start working to migrating this api, based on a config flag ofcourse

**Comment by Kurama622** [comment]
```lua
        user = "Kurama622",
        git_contributions = {
          start_week = 1,
          end_week = 53,
          empty_char = " ",
          full_char = { "", "󰧞", "", "", "" },
          fake_contributions = nil,
          non_official_api_cmd = [[curl -s https://github-contributions-api.jogruber.de/v4/%s | jq '.contributions' | jq --arg start $(date -d "1 year ago" +%%Y-%%m-%%d) --arg end $(date +%%Y-%%m-%%d) '.[] | select((.date >= $start) and (.date <= $end))' | jq -s 'sort_by(.date) | map(.count) | . as $array | reduce range(0; length; 7) as $i ({}; . + {($i/7+1 | tostring): $array[$i:$i+7]})']],
        },
```
you can fetch contributions without github tokens by non_official_api_cmd, this is an example

**Comment by Kurama622** [comment]
> ```lua
>         user = "Kurama622",
>         git_contributions = {
>           start_week = 1,
>           end_week = 53,
>           empty_char = " ",
>           full_char = { "", "󰧞", "", "", "" },
>           fake_contributions = nil,
>           non_official_api_cmd = [[curl -s https://github-contributions-api.jogruber.de/v4/%s | jq '.contributions' | jq --arg start $(date -d "1 year ago" +%%Y-%%m-%%d) --arg end $(date +%%Y-%%m-%%d) '.[] | select((.date >= $start) and (.date <= $end))' | jq -s 'sort_by(.date) | map(.count) | . as $array | reduce range(0; length; 7) as $i ({}; . + {($i/7+1 | tostring): $array[$i:$i+7]})']],
>         },
> ```
> 
> 你可以通过 non_official_api_cmd 获取没有 github token 的贡献，这是一个示例

But it's a bit slow, maybe my shell command is not efficient enough.
`$(date -d "1 year ago" +%%Y-%%m-%%d) ` :  
Different from the date format in the shell, I used the %%Y format because Lua needs to escape % .


You can generally implement your shell commands, maybe yours is more efficient.

**Comment by T0nd0Tara** [comment]
Thank you for the feature, and even more so for the command!

For the future users looking at this issue, you can slightly speed up the command by specifying only the years you want. ie.

`curl -s "https://github-contributions-api.jogruber.de/v4/%s?y=$(date -d "1 year ago" +%%Y)&y=$(date +%%Y)" | jq '.contributions' | jq --arg start $(date -d "1 year ago" +%%Y-%%m-%%d) --arg end $(date +%%Y-%%m-%%d) '.[] | select((.date >= $start) and (.date <= $end))' | jq -s 'sort_by(.date) | map(.count) | . as $array | reduce range(0; length; 7) as $i ({}; . + {($i/7+1 | tostring): $array[$i:$i+7]})'`

and even more by using a `jq` alternative

**Comment by T0nd0Tara** [comment]
For anyone that came across this issue wanting to do the same. I suggest using this command instead
```bash
curl -s "https://github-contributions-api.jogruber.de/v4/%s?y=$(date -d "1 year ago" +%%Y)&y=$(date +%%Y)" \
| jq --arg start $(date -d "1 year ago" +%%Y-%%m-%%d) --arg end $(date +%%Y-%%m-%%d) \
  '.contributions | [ .[] | select((.date >= $start) and (.date <= $end)) ] | sort_by(.date) | (.[0].date | strptime("%%Y-%%m-%%d") | strftime("%%w") | tonumber) as $wd | map(.level) | ([range(0, $wd) ] | map(0)) + . | . as $array | reduce range(0; length; 7) as $i ({}; . + {($i/7+1 | tostring): $array[$i:$i+7] })'
```
It is faster as it uses only one `jq` command instead of 3. Plus it shows more like what github shows on their site (i.e. each row is a week, not just 7 days)

If you'd like for it to be shown  when you're offline you can cache the result, see [this](https://github.com/T0nd0Tara/NvChadConfig/blob/Tara/scripts/get_github_contributions.sh) script as an example

**Comment by Kurama622** [comment]
The data it shows is different from what GitHub officially displays.

![non-official](https://github.com/user-attachments/assets/afd63966-7d9d-4fce-9da1-275b28f3b3bc)

![github](https://github.com/user-attachments/assets/71bf8a31-ef0d-4632-a527-4fe7b12850ed)

Perhaps there's something that needs to be adjusted, you can check it again. Once it's all set, you can submit a PR to update the readme. I think everyone should see your work.

**Comment by T0nd0Tara** [comment]
I believe this is because I use the contribution level instead of the count

I've looked in the [docs](https://docs.github.com/en/graphql/reference/objects#contributioncalendarday) for what should we use and it seems like the contribution level is the way to go.

I'd be happy to create a PR, just tell me if you rather I'd use the level or the count.

Btw, would it be ok if I add another config option for weather the plugin should cache the data if it was fetched less than a day ago?

**Comment by Kurama622** [comment]
1. Whether it's the count or the level of contribution, I think it's all right. I just used the count of contribution before, so let's keep it consistent by default. As for examples of obtaining the level of contribution, they can also be displayed. 

2. It's okay to cache the data for the day, and I look forward to your pull request.

**Comment by T0nd0Tara** [comment]
@Kurama622 I've made both pull request. I would love it if you'd review them

**Comment by Kurama622** [comment]
The code review is done, you can make some modifications, and ultimately, you need to confirm that the command can be executed: https://github.com/Kurama622/profile.nvim/pull/4

Regarding the PR for cache, here are some of my thoughts: There is no need to introduce third-party dependencies. You can add the date to the filename, and once the date does not match the current date, create a new cache file and delete the old cache file.

You can refer to some part of [the code](https://github.com/Kurama622/llm.nvim/blob/50714cce41ba06f578e1ab7310a4028d95052c8c/lua/llm/common/func.lua#L239-L259) from another plugin of mine, of course, it doesn't have to be as complex. You might not need character width conversion or handling of escape characters, and your final code might look something like this:

```lua
filename = string.format("%s/%s-%s.json", cache_path, user, os.date("%Y%m%d"))
local file = io.open(filename, "w")
file:write("some contents")
file:close()
```

**Comment by T0nd0Tara** [comment]
as for https://github.com/Kurama622/profile.nvim/pull/4 I fixed it. but for caching, isn't this way will make `cache_time` irrelevant? are you ok with it being hardcoded to 1 day?

**Comment by Kurama622** [comment]
https://github.com/Kurama622/profile.nvim/pull/4: I have merged it, but I found that this command doesn't work on macOS, perhaps because jq on macOS differs from Linux. I will try to make it compatible with Mac later.

**Comment by Kurama622** [comment]
Adding the date to the filename does not affect the cache_time logic, because the time in the filename can also be precise to the second, but I don't want to introduce a third-party dependency anymore. I have already relied on image.nvim, curl, and jq, although they are all optional, but it gives people the impression that the cost of use is high.

**Comment by Kurama622** [comment]
> #4: I have merged it, but I found that this command doesn't work on macOS, perhaps because jq on macOS differs from Linux. I will try to make it compatible with Mac later.

Macos should use `gdate`. I will update the readme later.

**Comment by T0nd0Tara** [comment]
> I don't want to introduce a third-party dependency anymore.

I couldn't find a good way to find the previous cache file (as I don't know the exact the name of it), that was also system independent.

so i changed it to save the modification time inside another file in the same folder called `.modification_timings`, and pushed it now, tell me what do you think

**Comment by Kurama622** [comment]
There will only be a unique cache file in the cache path, and each time the cache file is updated, the previous cache file will be deleted, as the filename includes a timestamp, making it easy to determine whether the current cache file needs to be updated.

**Comment by T0nd0Tara** [comment]
But how would you know if there was already a file there?

You can use `ls` (or any other command) but it is system dependent

Another way is trying to open all the files from `os.time() - cache_time` to `os.time()` but that wold take forever

**Comment by Kurama622** [comment]
`ls` is supported by default in Linux and Macos, and generally we don't consider Windows, and the curl and jq used by itself also exclude Windows, so I think it's OK to use `ls`. Maybe I'll write a version of the cache function later, and you'll see if it's OK, after all, this doesn't have much code



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/29/2024 23:27 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Kurama622/profile.nvim] The plugin requires Auth token (Issue #2) |

But how would you know if there was already a file there?

You can use ls (or any other command) but it is system dependent

Another way is trying to open all the files from os.time() - cache_time to os.time() but that wold take forever

**Comment by T0nd0Tara** [comment]
imo, the more you can make your plugin less system dependent the better. you now no longer have to use `curl` nor `jq` to use this plugin

but it is your decision.

**Comment by Kurama622** [comment]
https://github.com/Kurama622/profile.nvim/pull/6/files

Implement cache using the nvim API.


```lua
   git_contributions = {
      start_week = 1,
      end_week = 53,
      empty_char = "□",
      full_char = { "■", "■", "■", "■", "■" },
      fake_contributions = nil,
      non_official_api_cmd = nil,
      cache_path = "/tmp/profile.nvim/",
      cache_duration = 24 * 60 * 60, -- seconds
    },
```

**Comment by T0nd0Tara** [comment]
I wrote you a comment there. But anyway this looks pretty much the same as what I originally tried to merge (the one with lfs library) just using the neovim api

**Comment by Kurama622** [comment]
It's my tendency not to introduce dependencies as much as possible. When I discovered neovim's API, it would be more elegant to check the modification time than relying on the shell, so I went with the way you mentioned earlier



---- Replied Message ----
| From | ***@***.***> |
| Date | 12/01/2024 00:04 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [Kurama622/profile.nvim] The plugin requires Auth token (Issue #2) |

I wrote you a comment there. But anyway this looks pretty much the same as what I originally tried to merge (the one with lfs library) just using the neovim api

**Comment by Kurama622** [comment]
> I wrote you a comment there. But anyway this looks pretty much the same as what I originally tried to merge (the one with lfs library) just using the neovim api

Done

**Comment by T0nd0Tara** [comment]
Looks good!

**Comment by Kurama622** [comment]
Thank you for making this project better.
